Check wifi network when sending an http request
Waboodoo/HTTP-Shortcuts pull request #210
Opened 2021-01-07 19:38 UTC by crasu

I have different wifi networks at home and want to make sure I am connected to the correct one before sending out a http request. This makes it possible to configure a wifi network for a request.

2021-01-08 14:22 UTC, Waboodoo requested changes
Thanks for your contribution. This looks great. I left some comments for improvements.

2021-01-08 14:22 UTC, Waboodoo commented on HTTPShortcuts/app/src/main/kotlin/ch/rmy/android/http_shortcuts/activities/ExecuteActivity.kt
> +        val wifiManager = getSystemService(WIFI_SERVICE) as WifiManager
This line results in a warning in Android Studio, which suggests that `getSystemService` should be invoked from the `applicationContext`, not the activity context. As such, it should be changed to

```kotlin
val wifiManager = applicationContext.getSystemService(WIFI_SERVICE) as WifiManager
```

2021-01-08 14:22 UTC, Waboodoo commented on HTTPShortcuts/app/src/main/kotlin/ch/rmy/android/http_shortcuts/activities/ExecuteActivity.kt
> +import ch.rmy.android.http_shortcuts.http.*
Please leave the imports as they are. I prefer to have them explicit, as it makes it easier to find out where a specific class or function comes from.

2021-01-08 14:22 UTC, Waboodoo commented on HTTPShortcuts/app/src/main/kotlin/ch/rmy/android/http_shortcuts/activities/ExecuteActivity.kt
> +        Log.d("Wifi Connection", "Ssid: ${info.ssid}")
This needs to be removed

2021-01-08 14:22 UTC, Waboodoo commented on HTTPShortcuts/app/src/main/kotlin/ch/rmy/android/http_shortcuts/activities/ExecuteActivity.kt
> +       if(shouldShowRequestPermissionRationale(Manifest.permission.ACCESS_FINE_LOCATION))
There's a space missing between the `if` and the `(`

2021-01-08 14:22 UTC, Waboodoo commented on HTTPShortcuts/app/src/main/kotlin/ch/rmy/android/http_shortcuts/activities/ExecuteActivity.kt
> +            .message(String.format(getString(R.string.message_wrong_wifi_network), shortcut.ssid))
This can be simplified to

```kotlin
.message(getString(R.string.message_wrong_wifi_network, shortcut.ssid))
```

2021-01-08 14:22 UTC, Waboodoo commented on HTTPShortcuts/app/src/main/kotlin/ch/rmy/android/http_shortcuts/activities/ExecuteActivity.kt
> +
There's too many empty lines here

2021-01-08 14:22 UTC, Waboodoo commented on HTTPShortcuts/app/src/main/kotlin/ch/rmy/android/http_shortcuts/activities/ExecuteActivity.kt
> +
There's too many empty lines here

2021-01-08 14:22 UTC, Waboodoo commented on HTTPShortcuts/app/src/main/res/values/strings.xml
> +    <!-- Message: Shown to the user when connected to a different wifi network then the one given in the config -->
There's a typo here: should be "than" instead of "then"

2021-01-08 14:22 UTC, Waboodoo commented on HTTPShortcuts/app/src/main/kotlin/ch/rmy/android/http_shortcuts/activities/ExecuteActivity.kt
> +       if(shouldShowRequestPermissionRationale(Manifest.permission.ACCESS_FINE_LOCATION))
`shouldShowRequestPermissionRationale` requires at least Android SDK version 23, but the app needs to support back to 16. So here we should use the compatibility library:

```kotlin
if (ActivityCompat.shouldShowRequestPermissionRationale(this, Manifest.permission.ACCESS_FINE_LOCATION)) {
```

2021-01-08 14:22 UTC, Waboodoo commented on HTTPShortcuts/app/src/main/kotlin/ch/rmy/android/http_shortcuts/activities/ExecuteActivity.kt
> +                    emitter.onError(MissingPermissionException({ "Could not get location permission. Aborting request." }))
The error message should not be hardcoded but localized instead, see my other comment for `MissingPermissionException`.

2021-01-08 19:44 UTC, crasu commented
Thank you for your comments - I hope I addressed them all ...

2021-01-22 11:13 UTC, Waboodoo approved these changes
Thanks for the changes. I made some additional small changes so that it matches the code style of the rest of the app, as well as some minor tweaks to wording and the UI.

2021-01-22 11:15 UTC, merged